name: building-home-credit-default-risk-machine-learning-model
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pip=24.0
  - pip:
      - wandb==0.16.6
      - loguru==0.7.2
      - pandas==2.2.1
      - scikit-learn==1.4.2
      - matplotlib==3.8.4
      - omegaconf==2.3.0
      - loguru==0.7.2
      - mlflow==2.11.3
      - xgboost==2.0.3