name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests=2.31.0
  - pip=24.0
  - mlflow=2.11.3
  - hydra-core=1.3.2
  - pip:
      - wandb==0.16.6
      - loguru==0.7.2
      - opendatasets==0.1.22
      - omegaconf==2.3.0